<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>SQLGuardian.Cli</RootNamespace>
    <AssemblyName>sqlguardian</AssemblyName>
    <Description>SQLGuardian command-line analyzer.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SQLGuardian.RuleEngine\SQLGuardian.RuleEngine.csproj" />
    <ProjectReference Include="..\SQLGuardian.Abstractions\SQLGuardian.Abstractions.csproj" />
    <ProjectReference Include="..\SQLGuardian.Reporting\SQLGuardian.Reporting.csproj" />
    <ProjectReference Include="..\SQLGuardian.Schema\SQLGuardian.Schema.csproj" />
  </ItemGroup>

</Project>
